apiVersion: v2
name: pangeo
version: 0.0.1-set.by.chartpress
description: An extention of jupyterhub with extra Pangeo resources
dependencies:
  - name: jupyterhub
    version: "0.9.0"
    repository: 'https://jupyterhub.github.io/helm-chart/'
    import-values:
      - child: rbac
        parent: rbac
  - name: dask-gateway
    # Make sure to update the dask-gateway CRDs in .circleci/config.yml
    version: "0.7.1"
    repository: 'https://dask.org/dask-gateway-helm-repo/'
maintainers:
  - name: Jacob Tomlinson (Met Office)
    email: jacob.tomlinson@informaticslab.co.uk
  - name: Joe Hamman (NCAR)
    email: jhamman@ucar.edu
  - name: Guillaume Eynard-Bontemps (CNES)
    email: guillaume.eynard-bontemps@cnes.fr
  - name: Erik Sundell
    email: erik.i.sundell@gmail.com
