{{- if and (index .Values "dask-kubernetes" "enabled") .Values.rbac.enabled -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: daskkubernetes
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: daskkubernetes
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: daskkubernetes
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: daskkubernetes
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods/log"]
  verbs: ["get", "list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: daskkubernetes
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: daskkubernetes
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: daskkubernetes
roleRef:
  kind: Role
  name: daskkubernetes
  apiGroup: rbac.authorization.k8s.io
{{- end }}
